AllCops:
  SuggestExtensions: false
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false